# Docker Notes
# ============
# - `docker-compose up`: bring up containers
# - `docker-compose up -d`: same, but run in background/daemon mode
# - `docker-compose down`: bring down containers started with `-d`
# - `docker ps`: show running containers
# - `docker ps -a`: show all containers
# - `docker-compose exec <container name> /bin/bash`: get shell in app container
# - `docker images`
# - `docker rmi <image name>`
# - `docker stop $(docker ps -aq)`: stop all running containers
# - `docker rm $(docker ps -a -q)`: remove all stopped containers

version: '2'
services:
  flog-pg:
      image: postgres:12-alpine
      container_name: flog-pg
      ports:
        - '127.0.0.1:54321:5432'
      environment:
        # Kk for flog dev, potentially UNSAFE in other applications.  Don't blindly copy & paste
        # without considering implications.
        POSTGRES_HOST_AUTH_METHOD: trust
        # Could use this instead with a strong password if working outside a dev env
        # POSTGRES_PASSWORD: password
  flog-rabbitmq:
    image: rabbitmq:3.8-alpine
    container_name: flog-rabbitmq
    ports:
      - '127.0.0.1:56721:5672'
  flog-redis:
    image: redis:5-alpine
    container_name: flog-redis
    ports:
      - '127.0.0.1:63791:6379'
